### ISSUE TITLE
"ModuleNotFoundError"?

### ISSUE THREAD

**Issue by weijia-yao** [befelix/lyapunov-learning#1]
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-6449d19584ef> in <module>
      6 get_ipython().run_line_magic('matplotlib', 'inline')
      7 
----> 8 from safe_learning import *

lyapunov-learning/safe_learning/__init__.py in <module>
----> 1 from utilities import *
      2 from safe_learning import *

ModuleNotFoundError: No module named 'utilities'

**Comment by befelix** [comment]
I guess you're using Python 3. As far as I remember this library was mostly tested in python 2. I've just added a commit that should hopefully fix it for python 3, but I don't have time to test it. This is a fairly old repository that hasn't been used in a long time.

You might want to have a look at https://github.com/befelix/safe_learning
It implements some of the same stuff, but uses some of tensorflow's functinality to use it in a RL context.

**Comment by weijia-yao** [comment]
Thank you very much!
